.TH GHLSREPO "1" "JUNE 2025" "ghlsrepo" "User Commands"
.SH NAME
ghlsrepo \- list your github repositories 
.SH SYNOPSIS
.B ghlsrepo

.SH DESCRIPTION
.\" Add any additional description here
.PP
List your github repositories
.\" .SH OPTIONS
.\" .TP
.\" \fB\-x, --xxxxx\fR
.\" This is not really an option, this is just a template for the man
.\" page for when the real options get implemented.
.SH EXAMPLE
.nf
$ export GITHUB_USERNAME=jrandomdev
$ export GITHUB_TOKEN=github_pat_lksdjfkasdjflaskdfjalsdkfjalsdkfjalsdkfj-whatever
$ ghlsrepo
Fetching repositories for jrandomdev...
-                    matrix-mangler git@github.com:smcameron/matrix-mangler.git
-                    data-scrambler git@github.com:smcameron/data-scrambler.git
-                 auto-combobulator git@github.com:smcameron/auto-combobulator.git
$
.fi
.PP
.SH NOTES
This program is pretty rough and may not suit your needs at all.
.SH AUTHOR
Written by Google Gemini 2.5 Pro - https://gemini.google.com 
.br
